### ISSUE TITLE
Better performance in rgb for SAM demo, but worse in 3d slicer

### ISSUE THREAD

**Issue by LimitedLi** [bingogome/samm#50]
First of all, thank you very much for your excellent work.
But I noticed an interesting phenomenon that when we load a medical image with 3d slicer the segmentation we get is not good, but if I use the demo from the SAM website to do it with a screenshot of the medical image the result is very good.
Can you please explain the reason for this? This will help us to improve it, thanks!

**Comment by bingogome** [comment]
I am not sure the reason but perhaps it has something to do with the system glitch, which should be improved after the changes in: https://github.com/bingogome/samm/commit/5b63c7dfa120c39066215fb766f8b246be3e2414 

Theoretically they should be exactly the same if you put the same prompts. However that won't be the case because of scaling, intensity, coding of screenshot etc. End of the day they should be similar because there is not change in the network design.
